version: '3'

services:
    codeflix-catalog-admin-api:
        build: ./node
        container_name: codeflix-catalog-admin-api
        command: ./.docker/start.sh
        ports:
            - 3000:3000
        volumes:
            - ..:/home/node/app

    codeflix-catalog-admin-minio:
        image: minio/minio
        container_name: codeflix-catalog-admin-minio
        command: server /data --console-address ":9001"
        environment:
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=password
        ports:
          - "9000:9000"
          - "9001:9001"
        volumes:
            - ./minio/data:/data

    codeflix-catalog-admin-db:
        image: mysql:8.0.30-debian
        container_name: codeflix-catalog-admin-db
        environment:
            - MYSQL_DATABASE=catalog
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./mysql/data:/var/lib/mysql:delegated
        security_opt:
            - seccomp:unconfined

    codeflix-catalog-admin-db-tests:
        image: mysql:8.0.30-debian
        container_name: codeflix-catalog-admin-db-tests
        environment:
        - MYSQL_DATABASE=catalog
        - MYSQL_ROOT_PASSWORD=root
        tmpfs: /var/lib/mysql
        security_opt:
        - seccomp:unconfined
